### ISSUE TITLE
s.blitznote.com port 443: Connection refused

### ISSUE THREAD

**Issue by lbogdan** [Blitznote/docker-ubuntu-debootstrap#11]
I'm currently getting this error: `W: Failed to fetch https://s.blitznote.com/debs/ubuntu/amd64/all/InRelease  Failed to connect to s.blitznote.com port 443: Connection refused`.

**Comment by mark-kubacki** [comment]
Thanks — but please send an email in events like this.

The issue tracker is for bugs and ideas.
