### ISSUE TITLE
Unable to install iwatch

### ISSUE THREAD

**Issue by stereobooster** [Blitznote/docker-ubuntu-debootstrap#16]
Hi. Sorry to bother you again. This time it should be more valid question

```
FROM blitznote/debase:16.04
RUN apt-get update
RUN apt-get install libcommon-sense-perl liblinux-inotify2-perl iwatch
ENTRYPOINT iwatch -o ./ | xargs -n1 -I{} sh -c 'clear; printf "\033[3J" && /flow/flow'
```

I get this error

```
The following packages have unmet dependencies:
 libcommon-sense-perl : Depends: perl (< 5.24.2~) but 5.26.1-13bn is to be installed
E: Unable to correct problems, you have held broken packages.
The command '/bin/bash -c apt-get install libcommon-sense-perl liblinux-inotify2-perl iwatch' returned a non-zero code: 100
```

This is issue with Ubuntu, rather than your image. Asking just in case you can advice something, otherwise feel free to close it.

**Comment by mark-kubacki** [comment]
[See the README, section ›troubleshooting‹](https://github.com/Blitznote/debase/blame/029d93fc32cd3f19b7f0ebbc71ff81f767bb6d02/README.md#L75-L86). Thanks.

**Comment by mark-kubacki** [comment]
If you want a more recent **Perl** from Ubuntu (that is, not mine), I recommend you go with `blitznote/debase:18.04`.

**Comment by stereobooster** [comment]
Thank you for your patience ♥️

**Comment by mark-kubacki** [comment]
No biggie. I for one avoid *Perl* whenever possible. Not because it's good or bad, but to decrease complexity. And then, *Perl* enforces that modules be compiled with a particular minor version (modules for 5.24 won't be loaded by 5.26), which could have its reasons, but is a maintenance burden.
