### ISSUE TITLE
c++11 thread breakage on 18.04

### ISSUE THREAD

**Issue by GregBowyer** [Blitznote/docker-ubuntu-debootstrap#18]
I think 76bca5b164e7bb12f38c55216ff0058a6a24fcea breaks C++11 `std::thread`

Given the following test program

```c++
#include <thread>
#include <iostream>
void run() {
    std::cout << "thread" << std::endl;
}
int main(int argc, char** argv) {
    std::thread thrd(run);
    thrd.join();
    return 0;
}
```

Compiled like so with the 18.04 image

```bash
# docker run -it --rm blitznote/debase:18.04
apt-get -q update
apt-get -y --no-install-recommends install \
  g++

cat <<EOF > ./test.cc
#include <thread>
#include <iostream>
void run() {
    std::cout << "thread" << std::endl;
}
int main(int argc, char** argv) {
    std::thread thrd(run);
    thrd.join();
    return 0;
}
EOF

g++ -std=c++11 -o test -g3 -ggdb -pthread -Og ./test.cc
./test
```

You get a segmentation fault

Some programs will abort instead of seg-faulting e.g. [bazel](https://bazel.build)

```
11d59a839183 build $ bazel
Starting local Bazel server and connecting to it...
terminate called after throwing an instance of 'std::system_error'
  what():  Enable multithreading to use std::thread: Operation not permitted
Aborted (core dumped)
11d59a839183 build $
```

The same binaries pulled off the docker image and run locally will run just fine and wont segfault.
A local build of the project before 76bca5b164e7bb12f38c55216ff0058a6a24fcea allows the thread program to run correctly.

**Comment by mark-kubacki** [comment]
Awesome, thanks a lot!

I do confirm.

Interestingly `test` will work if compiled, and then run like this (I am using a new container here, without `gcc`, to see if `libstdc++6` is indeed the culprit):

```bash
# docker run -it --rm -v /tmp/artifacts:/build:ro blitznote/debase:18.04

$ /build/test
Segmentation fault (core dumped)

$ curl -fLR --remote-name-all \
    http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-8/{gcc-8-base,libstdc++6,libgcc1}_8.2.0-6ubuntu1_amd64.deb
$ apt-get -y --allow-downgrades install ./*.deb

$ /build/test
thread
```

My *gcc* is an unmodified re-compile of Ubuntu's, the only difference is other `-march=X -mtune=Y` (for amd64 {westmere,intel}; as does *Clear Linux*) and options introduced by new GCC releases, like `--enable-default-pie --enable-default-ssp `.

I will look into this later today.

**Comment by mark-kubacki** [comment]
Added to my CI/CD. If it doesn't fail, I will release a new revision of this base image.

If it fails, it could take a few hours for the automatic triaging to find whatever caused it. Or I will need to replace packages one by one for re-runs.

**Comment by mark-kubacki** [comment]
Automated triaging is 50% done. It's not the cpu optimizations but a combination of configuration options. `8.2.0` will stay, in case you wondered.

**Comment by mark-kubacki** [comment]
With `-Wl,-z,nodynamic-undefined-weak` identified as culprit, and with all checks passing, I will release a new revision in a few minutes.

Thanks again for bringing this issue to my attention!

**Comment by GregBowyer** [comment]
Awesome I am going to test this out shortly

For clarity, since we have special compilation here can we outline what the various flags are?

I am thinking:
`LDFLAGS`
`CXXFLAGS`
`CFLAGS`

??

**Comment by GregBowyer** [comment]
I am also seeing some linker fails in my build that might be an issue here

```
Use --sandbox_debug to see verbose messages from the sandbox: gcc-7 failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/865c972511bcdf170d7fc4305e0eeb92/execroot/bedrock && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PWD=/proc/self/cwd \
  /usr/bin/gcc-7 -o bazel-out/k8-fastbuild/bin/charon/charon/charon -pthread '-fuse-ld=gold' -Wl,-no-as-needed -Wl,-z,relro,-z,now -B/usr/bin -B/usr/bin -pass-exit-codes -m64 -m64 -Wl,@bazel-out/k8-fastbuild/bin/charon/charon/charon-2.params)

Use --sandbox_debug to see verbose messages from the sandbox
tmlib-core/os/socket.cpp:58: error: undefined reference to 'tmlib::os::runtime_error::runtime_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
tmlib-core/os/socket.cpp:651: error: undefined reference to 'tmlib::os::inet_address::inet_address(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned short)'
bazel-out/k8-fastbuild/bin/tmlib-core/_objs/tmlib-core/socket.pic.o:socket.cpp:vtable for tmlib::os::socket::socket_except: error: undefined reference to 'tmlib::os::exception::get_stack_trace[abi:cxx11]() const'
bazel-out/k8-fastbuild/bin/tmlib-core/_objs/tmlib-core/socket.pic.o:socket.cpp:vtable for tmlib::os::socket: error: undefined reference to 'tmlib::os::socket::get_last_error_string[abi:cxx11]() const'
collect2: error: ld returned 1 exit status
```

Any thoughts .. the linking comes out correct on normal ubuntu / rhel / etc

**Comment by mark-kubacki** [comment]
The build process for GCC does not use any custom flags, i. e. a `/etc/dpkg/buildflags.conf` is not used. (GCC and glibc are two exceptions that don't used it.)

Other than that, you get all used options by running `gcc -v`.

As to your error, I don't use *gcc-7* anymore. In any case, if you believe it's a package provided by me you'd need to open a new ticket with an excerpt of `dpkg --list` with what you're using.

**Comment by GregBowyer** [comment]
I get those linker errors with 7 and 8 FWIW

**Comment by mark-kubacki** [comment]
Google prefers *clang* for everything C++.

I've given it a try (edits mostly due to changed parameters of `docker`):

```bash
# docker pull blitznote/debase:16.04
# docker run -ti --rm -v /opt/bin:/target blitznote/debase:16.04
# ↑ is sha256:5df3aa9ee777e7c5b8d59734e7a02d768df13bc3042ad48dc0344d94610a726a

export PV=0.17.1

apt-get -q update
apt-get --no-install-recommends -y install \
  build-essential openjdk-8-jdk python \
  zip unzip
apt-get clean

cd /tmp
curl -fLRO https://s.blitznote.com/customer/self/src/bazel-${PV}-dist.zip \
|| curl -C - -fLRO https://github.com/bazelbuild/bazel/releases/download/${PV}/bazel-${PV}-dist.zip

mkdir -p /builds/bazel
cd $_
unzip /tmp/bazel-${PV}-dist.zip |& wc -l

bash ./compile.sh

# INFO: Elapsed time: 178.954s, Critical Path: 161.22s
# INFO: 1824 processes: 1518 local, 306 worker.
# INFO: Build completed successfully, 1910 total actions

mv output/bazel /target/
```

I guess you didn't use the latest container image?

**Comment by GregBowyer** [comment]
maybe I need more stuff from build-essential, let me test some more

**Comment by mark-kubacki** [comment]
What are you compiling using *bazel*?

**Comment by GregBowyer** [comment]
PEBUAK - I was making my minimal environment _too_ minimal

**Comment by mark-kubacki** [comment]
Throwaway containers is what I use for this. And a local mirror with packages. :-)

If you stumble upon something else – happy to look into.

**Comment by mark-kubacki** [comment]
FYI, I've added *Bazel* to my *canaries*, to the array of projects to be tested with new releases of this baseimage.

[![pipeline status](https://hub.blitznote.com/mark/bazelbuild/badges/master/pipeline.svg)](https://hub.blitznote.com/mark/bazelbuild/commits/master) – [gitlab:mark/bazelbuild](https://hub.blitznote.com/mark/bazelbuild/pipelines/4067)
