### ISSUE TITLE
Given a baseimage, how can I build one myself?

### ISSUE THREAD

**Issue by tiadobatima** [Blitznote/docker-ubuntu-debootstrap#2]
I really like what you did here to make Ubuntu images less bloated. Very good job! But in order for us to be able to deploy this we'd need to know how rootfs.tar.xz is built (for regulatory reasons we'd need to build images in house). I understand if you want to keep the secret, but I'm wondering if instead of having the rootfs.tar.xz checked into git, you'd have the script that builds it. Or maybe just shared how rootfs.tar.xf is built?

Cheers!

**Comment by mark-kubacki** [comment]
If the regulator is a body of Germany then please contact me by email with details: A majority of my work is already certified or has already been audited and it's easy to obtain placets by showing _equivalency_ or the derivative work being a _subset._

**Comment by mark-kubacki** [comment]
As outlined in the README you can build the images yourself using a few tools already provided by Ubuntu:

``` bash
#!/bin/bash
# recreate.sh – this file – creates the configuration file needed by tool "multistrap"
set -euo pipefail

WORKDIR="$(mktemp -d -t "ubuntu.XXXXXX")"

cat >multistrap.conf <<EOF
[General]
arch=amd64
noauth=true
cleanup=true
directory=$WORKDIR
debootstrap=
aptsources=
omitrequired=false

EOF

# For better legibility omit IJEFOQUV.
ordinals=("repoA" "repoB" "repoC" "repoD" "repoG")

n=0
while read source suite components; do
  sed -i \
    -e "/^debootstrap/s:\$: ${ordinals[$n]}:" \
    -e "/^aptsources/s:\$: ${ordinals[$n]}:" \
    multistrap.conf
  cat >>multistrap.conf <<EOP
[${ordinals[$n]}]
packages=
source=$source
suite=$suite
components=$components
omitdebsrc=true

EOP
  let n+=1
done < <(cat /etc/apt/sources.list | sed -n '/^deb/s/.*\(http.*\)/\1/p' | sort -u)

packages=($(gzip -dc /var/log/installer/initial-status.gz | sed -n 's/^Package: //p' | sort -u))
sed -i \
  -e "0,/^packages=/s:packages=:packages=${packages[*]}:" \
  multistrap.conf

printf "Run multistrap, inspect its results, and then:\n"
printf "  tar --one-file-system --sort=name \\ \n"
printf "    -C '%s' -caf rootfs.tar .\n" "${WORKDIR}"
```

(It's okay to have lines with an empty right side of `packages=`.)

``` bash
bash ./recreate.sh            # creates the configuration file needed below

apt-get -q update
apt-get -y install multistrap # run this after recreate.sh!

multistrap -f multistrap.conf # assembles an Ubuntu baseimage (aka "stage 1")
```

… and you will have everything in a temporary directory, ready for **tar**.

The resulting tarball is ⊇ `rootfs.tar.*` ∖ `contrib/*` ∖ symlinks ∖ configuration files. The latter are ≤10 files.

**Comment by tiadobatima** [comment]
Brilliant. This is exactly what I was looking for. Thank you very much @wmark! And no, unfortunately we're in US/Canada.
Thank you very much again!

**Comment by mark-kubacki** [comment]
Keep in mind you will get installed more than necessary:
- Ubuntu's maintainers sometimes add requirements to packages which are not really _requirements_, but should've been marked as _suggestions_ instead. Uninstall something like `mount` or `libudev1`.
- As Docker/rkt/runC images are not used for interactive systems, you don't need packages like `login` or `askpass`.
- … nor are – for example – any translation files (`*.po *.mo`) needed if you're fine with a default locale. (Most DevOps will debug or browse manpages using a separate installation anyway.)

Pruning those packages and deleting those excess files is something I do on a case-by-case basis. In a gist, everything that's not in the supplied `build.manifest` has been removed using `apt remove…`. This will yield a list of said cruft and uninstall it:

``` bash
excess=($(comm -23 <(apt-mark showmanual | sort -u) <(cat build.manifest | cut -f 1)))
for pkg in ${excess[@]}; do
  apt-get remove "${pkg}"
done
```

… if you use `find -type f` vs `tar -tvf rootfs.tar` you get a list of files I've removed.

**Comment by tiadobatima** [comment]
Yeah.... iterating over the packages that should be removed without breaking package dependency is where the "fun" is. When I tried doing this using the [official Ubuntu base root FS tarball](http://cdimage.ubuntu.com/ubuntu-base/xenial/daily/current/), I got quite a few dependency errors/warnings that made me quite uncomfortable trusting the image would be useful.

**Comment by mark-kubacki** [comment]
Hence my guidance to use the supplied `build.manifest`. 😉 

You will notice that the packages needed for a minimal Ubuntu are almost a constant. If you were to examine all packages, you would arrive at the same list as I. Except perhaps for packages that add utility like `curl` or `unzip` and substitutes.

---

A minimal _Linux_ distribution, that is if we were to remove `apt` (or any other package manager) and its dependencies `gpg`, `perl`, and friends, is even smaller. You would build it by starting with `libc6`, a shell (or busybox), and other base packages (for `libstc++`, timezones, `/etc/services`, `/etc/mime*`…), and pull in their dependencies. I've done that and arrived at something ≤32 MiB.
It's not worthwile, though, because the user will need to get binaries for downloading (curl), extracting (bzip2, xz), and verifying of downloads (gpg) anyway – and effectively ship the old X MiB merely distributed differently, despite the efforts.

If a developer does not need _glibc_ she/he is better off using a distribution that comes with _µclibc_, _musl_, or even _dietlibc_. (Which did not enjoy as many optimizations as _glibc_ did.)

**Comment by tiadobatima** [comment]
Totally! Thank you very much @wmark! 👍 
I wish the Ubuntu folks would take look at what you did, and tried to slim down the size of the base root FS!
