### ISSUE TITLE
Unable to run apt-get update with current image (4890484dbe94)

### ISSUE THREAD

**Issue by javmorin** [Blitznote/docker-ubuntu-debootstrap#4]
Just found this base image linked over from comments on the phusion baseimage but ran into some trouble. I went to install some things via apt but `docker build .` fails with the following output:
```
$ docker build .
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM blitznote/debootstrap-amd64:16.04
 ---> 4890484dbe94
Step 2 : RUN apt-get -q update
 ---> Running in 80425c31cdb9
Reading package lists...
E: Method http has died unexpectedly!
E: Sub-process http received signal 4.
```

I took a brief look at the container fs contents and noticed that there is no /etc/apt directory or related files. I I read through the readme and there was no indication of a special way to run apt, so now I am stuck. I see other docker projects using this as a base image with no indication of special instructions to get apt working.

Would appreciate any clues

Edit:
I was mistaken about the missing APT files, I was looking at the wrong FS layer.  I have started a container directly with this image and can confirm the files seem to be present, but apt-get update errors out as above.

**Comment by javmorin** [comment]
Looks like it's the SSE4 compatibility issue. I am running this on a pre-2011 Opteron, so it may not have the necessary instruction set. Closing this now, will look elsewhere for an image to use.

**Comment by mark-kubacki** [comment]
Thanks for your feedback!

In the past I've seen error message `illegal instruction` on killed processes due to them using unavailable instructions. A `sub-process died unexpectedly` is certainly worth noting somewhere as a variant of the symptom. (I guess search engines will index this ticket, so it's hereby done.)

**Comment by mark-kubacki** [comment]
FYI, if you run `dmesg` then you will see a log entry like `trap invalid opcode` for this.
