### ISSUE TITLE
apt-get: W: Conflicting distribution

### ISSUE THREAD

**Issue by TimVNL** [Blitznote/docker-ubuntu-debootstrap#5]
Hi, 

Im am busy with my own docker image and I really like your base :)

But I get the following error when using apt on 16.04

```
W: Conflicting distribution: https://s.blitznote.com/debs/ubuntu/amd64 all/ InRelease  
(expected all/ but got )
```

any fix?

**Comment by mark-kubacki** [comment]
Thanks for reminding me of this.

This is merely a warning about a missing field in my repository's file `InRelease`. It's no error and everything works as expected.

I will update the scripts for the repo (not included or related to this base image) on the next occasion. Probably when **apt** drops *sha1-* and *md5sum* from the file in favour of *blake2*.

----
For my notes:
 * https://git.launchpad.net/apt/tree/methods/gpgv.cc?id=1.4.1#n67

**Comment by hshopeful** [comment]
@wmark hi, 
I construct one repo on my server A, and set the other server B's 
`/etc/apt/sources.list.d/***.list`  as follows:
`deb http://xxx.xxx.xxx.xxx:19996/deb/ all main `

on server B(ubuntu14.04) , when I run the command "apt-get update"，warming appears:
`W: Conflicting distribution: http://xxx.xxx.xxx.xxx:19996 all InRelease (expected all but got )`

on my server A, `InRelease` file is as follows:
`-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Date: Mon, 19 Jun 2017 12:17:34 +0800
MD5Sum:
 263add3fbd75eb167bdc062d4d539c5c	1379 main/binary-amd64/Packages
 94a3106627871b795a43c96fafb56c4d	750 main/binary-amd64/Packages.gz
SHA1:
 b602d2fcf9fdf4779c1a935b6ac614f7d04b8ed2	1379 main/binary-amd64/Packages
 d0872eb747d94862295f6863ad77e1116fdeba6a	750 main/binary-amd64/Packages.gz
SHA256:
 ef0d792c1f8fd6f8dcac9f1ab8acd4cc70f226909ddc04b9b635d1cee89ea4b1	1379 main/binary-amd64/Packages
 a177ffc635e3e4f7173fc4d3eb02ccb471bded007433cfb1d22654e49b70c265	750 main/binary-amd64/Packages.gz
SHA512:
 1d20753d762e33221b8ead1626626c95bae838d632b10fa033ee98c991a29857a4826388e0472043b8efa06dcbfcf17d4be9ab328abaa6eff5526acf783937de	1379 main/binary-amd64/Packages
 d649f778233caf6465457f35d210b851cf773d14d1f9b069255e04ef73f44014780f09a10c805b5fbc7411aa442d841c9c48e256823eb1bcae416d3fc2cc2d80	750 main/binary-amd64/Packages.gz
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2.0.14 (GNU/Linux)

iQEcBAEBCAAGBQJZR1BiAAoJEOaMuYdzRcFe5JcIALC0YDNL2CUVue2AEbvlcRpp
P54ncmr4/AsfPCUfVZtOQk5W7HNaife7r7PNhRafJAmu5VO0q4XPhCZWtDpw4bZJ
82WP+TcdZ2YYhui9eVf7fA5frLRXE5ZY+rMKavu7hLHr00/T087BSDHia7Lhj0Jr
ZAyFk11GIMGMNPIbhwFJ74DujYYO/73QrpnQf083gT4N0NOmI+ryB0v0k2NoLFdl
2zaLXIY5j6Bdl71bllqhHHxyFyASChEr+z/Ylzev3EYn18FTkSs6oj9jNuxRmdc0
Qxzq5fq4vDTOQQOsh8uqAwM2W35z2rlHX479XlCPDx4ZjWQ1UO4NnTuw8BGTAK8=
=J0ri
-----END PGP SIGNATURE-----`

could you help to point out which field is missing in my `InRelease` file

Thank you

**Comment by mark-kubacki** [comment]
Refreshed baseimages are being currently tested, and an updated revision is due this Thu/Fri.
