### ISSUE TITLE
Unable to install build-essential

### ISSUE THREAD

**Issue by creategui** [Blitznote/docker-ubuntu-debootstrap#6]
My Dockerfile:
```docker
FROM blitznote/debootstrap-amd64:16.04
RUN apt-get update \
 && apt-get install -y \
      build-essential \
```

The Error:
```
The following packages have unmet dependencies:
 build-essential : Depends: libc6-dev but it is not going to be installed or
                            libc-dev
                   Depends: g++ (>= 4:5.2) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by mark-kubacki** [comment]
Confirmed, can reproduce. Images in staging have already moved past this: It's solved but not published yet.

**Comment by mark-kubacki** [comment]
I've edited your report, minimized the supplied dockerfile and added formatting.

BTW, don't use `apt-get upgrade` in dockerfiles. It's a bad practice.
Any derived image should be rebuild on rebuilds of its parent image(s).

**Comment by creategui** [comment]
Thanks.  I don't normally use _upgrade_.  I just added it to see if it made a difference for this issue and left it there, my bad.

**Comment by mark-kubacki** [comment]
New baseimages are up.
