### ISSUE TITLE
default language

### ISSUE THREAD

**Issue by DanielRuf** [Blitznote/docker-ubuntu-debootstrap#7]
It seems the image uses Ukrainian instead of English or something else, is there some setting to change this or planned to set to to English?

See https://github.com/knq/chrome-headless/issues/1

**Comment by mark-kubacki** [comment]
It already is in English, and you are looking into the wrong thing I am afraid.

The base images don't come with any translations, and indeed (quote from the README file) `with locale ISO.UTF-8 as default` (for locale-aware programs; else it's `C` or `POSIX`).  
Which changes the date format to `2017-08-02` and similar. Furthermore, a quick look reveals:

```bash
$ docker run -ti --rm blitznote/debootstrap-amd64:16.04 locale -a
C
ISO.utf8
POSIX

$ docker run -ti --rm blitznote/debootstrap-amd64:16.04
$ locale
LANG=ISO.UTF-8
LANGUAGE=
LC_CTYPE="ISO.UTF-8"
LC_NUMERIC="ISO.UTF-8"
LC_TIME="ISO.UTF-8"
LC_COLLATE="ISO.UTF-8"
LC_MONETARY="ISO.UTF-8"
LC_MESSAGES="ISO.UTF-8"
LC_PAPER="ISO.UTF-8"
LC_NAME="ISO.UTF-8"
LC_ADDRESS="ISO.UTF-8"
LC_TELEPHONE="ISO.UTF-8"
LC_MEASUREMENT="ISO.UTF-8"
LC_IDENTIFICATION="ISO.UTF-8"
LC_ALL=
```

Please do your due diligence before opening bugs or claiming things. The dev who commented right above you in the original issue has not been able to reproduce this, too.

**Comment by DanielRuf** [comment]
Well, I pulled a fresh Docker image from your project and the output with curl in the container from this images already has this ua redirect. Independent of the chrome-headless.

**Comment by DanielRuf** [comment]
```
docker run blitznote/debootstrap-amd64:16.10 curl www.google.com
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   262  100   262    0     0    262      0  0:00:01 --:--:--  0:00:01  1224
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="http://www.google.com.ua/?gfe_rd=cr&amp;ei=f7GBWbDAHs7CgASKuo-oBw">here</A>.
</BODY></HTML>
```

Pulled the image today. The same command on the host redirects to .de, not .com.ua.

**Comment by DanielRuf** [comment]
Very weird. On a MacOS host of a colleague with a german language the Docker container gets the german redirect. But the host that I use (Hetzner server, en locale) gets the ua redirect in the Docker image.

**Comment by mark-kubacki** [comment]
Sorry, I don't see the relation between the provided Docker image(s) and redirects from websites of third parties. On top of that your original report has been about output in unexpected Cyrillic chars.

To my latest knowledge *curl* doesn't set any `Accept-Language` headers of its own. If it did you'd see them shown by `curl --verbose …`. IP-to-country mapping by third parties is certainly out of scope of my images.

> Very weird. On a MacOS host of a colleague with a german language the Docker container gets the german redirect. But the host that I use (Hetzner server, en locale) gets the ua redirect in the Docker image.

The binaries contained in these Docker images will run on Linux only. As far as I know MacOS is a different kind of thing.

**Comment by DanielRuf** [comment]
> The programs contained in these Docker images will run on Linux only. As far as I know MacOS is a different kind of thing.

If you mean Docker and the image, the command also works on MacOS hosts where we use the Docker image of you.

The host which runs your Docker image has en locale and a german IP address and a curl outside of the Docker container redirects to google.de but inside the Docker container with your image it redirects to google.com.ua (but so far not reproducible on hosts with locale set to de) which is really weird (host where this happens is a Debian server).

**Comment by DanielRuf** [comment]
```
curl www.google.com --verbose
* Rebuilt URL to: www.google.com/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 74.125.21.147...
* TCP_NODELAY set
* Connected to www.google.com (74.125.21.147) port 80 (#0)
> GET / HTTP/1.1
> Host: www.google.com
> User-Agent: curl/7.54.1-154
> Accept: */*
>
< HTTP/1.1 302 Found
< Cache-Control: private
< Content-Type: text/html; charset=UTF-8
< Referrer-Policy: no-referrer
< Location: http://www.google.com.ua/?gfe_rd=cr&ei=-bmBWZWACNPAgATE8ZSIDg
< Content-Length: 262
< Date: Wed, 02 Aug 2017 11:39:37 GMT
<
{ [262 bytes data]
100   262  100   262    0     0    262      0  0:00:01 --:--:--  0:00:01  1224
* Connection #0 to host www.google.com left intact
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="http://www.google.com.ua/?gfe_rd=cr&amp;ei=-bmBWZWACNPAgATE8ZSIDg">here</A>.
</BODY></HTML>
```

**Comment by mark-kubacki** [comment]
Excellent. You see, no environment is part of the request, yet you get the unwanted redirect.

I highly suggest you revisit my hints from my above comments. Closing this for good now because you're running in circles.
