### ISSUE TITLE
i386 architecture?

### ISSUE THREAD

**Issue by magick93** [Blitznote/docker-ubuntu-debootstrap#8]
Hello

Do you have any pointers on how to build a i386 image ?

Im currently using i386's which are somewhat larger.

Thanks

**Comment by mark-kubacki** [comment]
No, sorry. You'd build it the same way images for *amd64* are built.

But please ask something like this by email.

**Comment by magick93** [comment]
Ok, thanks. 

Please tell me, what email address should I use? I could not see any mention of a mailing list.

Thanks

**Comment by mark-kubacki** [comment]
Its literally part of every *commit* of mine, and prominently shown in my Github profile if you're logged in.

**Comment by mark-kubacki** [comment]
Releases for i386 (32b) won't happen in the foreseeable future: There are no servers nor IoT devices announced for this architecture. Intel has even discontinued its *Edison* line, which has been the last somewhat »modern« target platform where you'd use a container runtime (such as *Docker* or *rkt*).
